/**
 * export-utils.ts
 * Shared CSV and PDF export helpers used across all reporting modules.
 * CSV follows RFC 4180. PDF uses jspdf + jspdf-autotable.
 */

// ─── CSV ─────────────────────────────────────────────────────────────────────

/** Sanitize a single cell value: strip newlines, trim, escape quotes per RFC 4180 */
function sanitizeCell(value: unknown): string {
  const str = String(value ?? "")
    .replace(/\r?\n|\r/g, " ") // replace newlines with space
    .trim();
  // Escape internal double-quotes by doubling them, then wrap in quotes
  return `"${str.replace(/"/g, '""')}"`;
}

/** Capitalize the first letter of a string, lowercase the rest */
export function capitalize(str: string): string {
  if (!str) return "";
  return str.charAt(0).toUpperCase() + str.slice(1).toLowerCase();
}

/** Title-case each word, e.g. WORKSHOP → Workshop */
export function titleCase(str: string): string {
  return str
    .toLowerCase()
    .replace(/_/g, " ")
    .split(" ")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
}

/** Build a BOM-prefixed RFC 4180 CSV blob and trigger a download */
export function downloadCSV(headers: string[], rows: unknown[][], filename: string): void {
  const BOM = "\uFEFF"; // UTF-8 BOM — ensures Excel recognises encoding
  const csvLines = [headers, ...rows].map((row) =>
    row.map(sanitizeCell).join(",")
  );
  const csvContent = BOM + csvLines.join("\r\n"); // RFC 4180 uses CRLF
  const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/** Generate a safe filename-friendly date string: YYYY-MM-DD */
export function isoDate(): string {
  return new Date().toISOString().split("T")[0];
}

/** Slugify a string for use in filenames */
export function slugify(str: string): string {
  return str
    .trim()
    .replace(/\s+/g, "_")
    .replace(/[^a-zA-Z0-9_-]/g, "")
    .slice(0, 60);
}

// ─── PDF ─────────────────────────────────────────────────────────────────────

export interface PdfColumn {
  header: string;
  dataKey: string;
}

export interface PdfOptions {
  title: string;
  subtitle?: string;
  generatedBy?: string;
  summaryItems?: Array<{ label: string; value: string | number }>;
  columns: PdfColumn[];
  rows: Record<string, unknown>[];
  filename: string;
}

/**
 * Generate a styled PDF report using jsPDF + jspdf-autotable.
 * Dynamically imports to keep the initial bundle lean.
 */
export async function downloadPDF(opts: PdfOptions): Promise<void> {
  // Lazy load — avoids adding jspdf to the critical path
  const { default: jsPDF } = await import("jspdf");
  const autoTableModule = await import("jspdf-autotable");
  const autoTable = autoTableModule.default;

  const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  // ── Colours ───────────────────────────────────────────────────
  const PRIMARY = [30, 58, 138] as [number, number, number];    // navy
  const LIGHT   = [239, 246, 255] as [number, number, number];  // pale blue
  const WHITE   = [255, 255, 255] as [number, number, number];
  const GRAY    = [107, 114, 128] as [number, number, number];
  const DARK    = [17, 24, 39] as [number, number, number];

  // ── Header band ───────────────────────────────────────────────
  doc.setFillColor(...PRIMARY);
  doc.rect(0, 0, pageWidth, 28, "F");

  doc.setTextColor(...WHITE);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text("Event Management System", 14, 11);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(opts.title, 14, 19);
  if (opts.subtitle) {
    doc.setFontSize(8);
    doc.text(opts.subtitle, 14, 25);
  }

  // date + generated by — right-aligned
  const dateStr = `Generated: ${new Date().toLocaleString()}`;
  const byStr = opts.generatedBy ? `By: ${opts.generatedBy}` : "";
  doc.setFontSize(8);
  doc.text(dateStr, pageWidth - 14, 19, { align: "right" });
  if (byStr) doc.text(byStr, pageWidth - 14, 25, { align: "right" });

  let cursorY = 36;

  // ── Summary cards ─────────────────────────────────────────────
  if (opts.summaryItems && opts.summaryItems.length > 0) {
    const cardW = (pageWidth - 28 - (opts.summaryItems.length - 1) * 4) / opts.summaryItems.length;
    opts.summaryItems.forEach((item, i) => {
      const x = 14 + i * (cardW + 4);
      doc.setFillColor(...LIGHT);
      doc.roundedRect(x, cursorY, cardW, 16, 2, 2, "F");
      doc.setTextColor(...PRIMARY);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(12);
      doc.text(String(item.value), x + cardW / 2, cursorY + 7, { align: "center" });
      doc.setTextColor(...GRAY);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(7);
      doc.text(item.label, x + cardW / 2, cursorY + 13, { align: "center" });
    });
    cursorY += 22;
  }

  // ── Data table ────────────────────────────────────────────────
  autoTable(doc, {
    startY: cursorY,
    head: [opts.columns.map((c) => c.header)],
    body: opts.rows.map((row) => opts.columns.map((c) => String(row[c.dataKey] ?? ""))),
    styles: {
      fontSize: 8,
      cellPadding: 3,
      textColor: DARK,
      lineColor: [209, 213, 219],
      lineWidth: 0.2,
    },
    headStyles: {
      fillColor: PRIMARY,
      textColor: WHITE,
      fontStyle: "bold",
      fontSize: 8.5,
    },
    alternateRowStyles: {
      fillColor: LIGHT,
    },
    margin: { left: 14, right: 14 },
    tableWidth: "auto",
  });

  // ── Footer ────────────────────────────────────────────────────
  const totalPages: number = (doc.internal as any).getNumberOfPages();
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p);
    doc.setFillColor(...PRIMARY);
    doc.rect(0, pageHeight - 12, pageWidth, 12, "F");
    doc.setTextColor(...WHITE);
    doc.setFontSize(7);
    doc.text("Confidential — For internal use only", 14, pageHeight - 5);
    doc.text(`Page ${p} of ${totalPages}`, pageWidth - 14, pageHeight - 5, { align: "right" });
  }

  doc.save(opts.filename);
}
